from django.contrib import admin
from .models import *
# Register your models here.
# admin.site.register(Instructor)
# admin.site.register(Course)
admin.site.register(Publication)
admin.site.register(Article)
admin.site.register(snippet)
admin.site.register(Modules)
admin.site.register(StudentforModule)
admin.site.register(apiviewmodel)
admin.site.register(Authmodel)
admin.site.register(Province)
admin.site.register(City)
admin.site.register(Books_model)
admin.site.register(Store_model)
admin.site.register(employee)
admin.site.register(Men)
admin.site.register(Women)
admin.site.register(Languages)
admin.site.register(Percent_Module_Complete)
admin.site.register(Sports)
admin.site.register(Student)
admin.site.register(CourseforStudent)
admin.site.register(Enrollement)