# Generated by Django 4.1.1 on 2022-09-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appis221', '0005_modules_alter_course_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentformodule',
            name='modules',
        ),
        migrations.AddField(
            model_name='studentformodule',
            name='modules1',
            field=models.ManyToManyField(related_name='studentwithmodule', to='appis221.modules'),
        ),
    ]
