# Generated by Django 4.1.1 on 2022-09-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appis221', '0006_remove_studentformodule_modules_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentformodule',
            old_name='modules1',
            new_name='modules',
        ),
    ]
