# Generated by Django 4.1.1 on 2022-10-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appis221', '0007_rename_modules1_studentformodule_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
