# Generated by Django 4.1.1 on 2022-10-03 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appis221', '0008_modules_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 3, 10, 58, 43, 59968, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
