# Generated by Django 4.1.1 on 2022-10-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appis221', '0011_alter_modules_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
