# Generated by Django 4.1.1 on 2022-10-04 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appis221', '0014_alter_modules_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentformodule',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentformodule',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 4, 11, 17, 14, 367265), null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 4, 11, 17, 14, 367265), null=True),
        ),
    ]
