# Generated by Django 4.1.1 on 2022-10-04 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appis221', '0015_studentformodule_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 4, 11, 24, 55, 199407), null=True),
        ),
        migrations.AlterField(
            model_name='studentformodule',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 4, 11, 24, 55, 199407), null=True),
        ),
    ]
