# Generated by Django 4.1.1 on 2022-10-04 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appis221', '0018_alter_modules_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentformodule',
            name='created_at_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 4, 11, 46, 58, 584690), null=True),
        ),
        migrations.AlterField(
            model_name='studentformodule',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 4, 11, 46, 58, 584690), null=True),
        ),
    ]
