# Generated by Django 4.1.1 on 2022-10-04 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appis221', '0020_apiviewmodel_alter_modules_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiviewmodel',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 4, 15, 25, 19, 222412), null=True),
        ),
        migrations.AlterField(
            model_name='studentformodule',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 4, 15, 25, 19, 222412), null=True),
        ),
    ]
