# Generated by Django 4.1.1 on 2022-10-06 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appis221', '0022_alter_modules_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentformodule',
            name='created_at_date',
        ),
        migrations.AlterField(
            model_name='modules',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 6, 18, 45, 57, 686813), null=True),
        ),
        migrations.AlterField(
            model_name='studentformodule',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 6, 18, 45, 57, 686813), null=True),
        ),
    ]
