# Generated by Django 4.1.1 on 2022-10-21 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appis221', '0030_books_model_alter_modules_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 21, 16, 15, 40, 725222), null=True),
        ),
        migrations.AlterField(
            model_name='store_model',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, related_name='storeset', to='appis221.books_model'),
        ),
        migrations.AlterField(
            model_name='studentformodule',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 21, 16, 15, 40, 725222), null=True),
        ),
    ]
