# Generated by Django 4.1.1 on 2022-10-26 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appis221', '0034_alter_modules_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 26, 11, 13, 17, 141496), null=True),
        ),
        migrations.AlterField(
            model_name='studentformodule',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 26, 11, 13, 17, 141496), null=True),
        ),
    ]
