# Generated by Django 4.1.1 on 2022-10-28 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appis221', '0035_alter_modules_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(blank=True, null=True, related_name='Article_set', to='appis221.publication'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 28, 8, 21, 42, 548835), null=True),
        ),
        migrations.AlterField(
            model_name='studentformodule',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 28, 8, 21, 42, 548835), null=True),
        ),
    ]
