# Generated by Django 4.1.1 on 2022-10-28 15:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appis221', '0037_men_alter_modules_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Percent_Module_Complete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_complete', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=40)),
                ('sport_coach', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='studentformodule',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 28, 21, 29, 21, 578646), null=True),
        ),
        migrations.AlterField(
            model_name='studentformodule',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 28, 21, 29, 21, 578646), null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='percentage_completion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appis221.percent_module_complete'),
        ),
        migrations.AddField(
            model_name='studentformodule',
            name='languages_spoken',
            field=models.ManyToManyField(blank=True, null=True, to='appis221.languages'),
        ),
        migrations.AddField(
            model_name='studentformodule',
            name='sports_registered',
            field=models.ManyToManyField(blank=True, null=True, related_name='Studentformodule_set', to='appis221.sports'),
        ),
    ]
