# Generated by Django 4.1.1 on 2022-10-30 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appis221', '0039_courseforstudent_student_alter_modules_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='languages_spoken',
            field=models.ManyToManyField(blank=True, null=True, to='appis221.languages'),
        ),
        migrations.AddField(
            model_name='student',
            name='sports',
            field=models.ManyToManyField(blank=True, null=True, to='appis221.sports'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 8, 58, 50, 134389), null=True),
        ),
        migrations.AlterField(
            model_name='studentformodule',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 8, 58, 50, 134389), null=True),
        ),
    ]
