# Generated by Django 4.1.1 on 2022-10-30 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appis221', '0040_student_languages_spoken_student_sports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 10, 10, 26, 422524), null=True),
        ),
        migrations.AlterField(
            model_name='studentformodule',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 10, 10, 26, 422524), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='enrollement',
            unique_together={('course', 'student')},
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
