# Generated by Django 4.1.1 on 2022-10-30 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appis221', '0041_alter_modules_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sports',
            name='sport_coach',
        ),
        migrations.AlterField(
            model_name='modules',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 10, 29, 26, 281417), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='languages_spoken',
            field=models.ManyToManyField(blank=True, null=True, related_name='Studentsetfor_languages', to='appis221.languages'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sports',
            field=models.ManyToManyField(blank=True, null=True, related_name='Studentsetfor_sports', to='appis221.sports'),
        ),
        migrations.AlterField(
            model_name='studentformodule',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 10, 29, 26, 281417), null=True),
        ),
    ]
